version: '3.9'

services:
  worker-api:
    container_name: worker-api
    build: ./app
    restart: unless-stopped
    env_file:
      - ./api.env
      - ./db.env
    ports:
      - 3000:3000
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - service
      - internal
    depends_on:
      - worker-db

  worker-db:
    container_name: worker-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - ./db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  service:
  internal:
