version: '3.9'

services:
  workers-api:
    container_name: workers-api
    build: ./app
    restart: unless-stopped
    env_file:
      - ./api.env
      - ./db.env
    ports:
      - 3000:3000
    networks:
      - service
    depends_on:
      - workers-db

  workers-db:
    container_name: workers-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - ./db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - service

networks:
  service:
