name: "Linter"

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [ master ]

jobs:
  quality-prettier:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.version }}

      - name: Install prettier
        run: cd app; yarn

      - name: Check prettier
        run: cd app; yarn run linter
